### ISSUE TITLE
New cmdlet Request : Dissociate "Set-Secret" from "New-Secret"

### ISSUE THREAD

**Issue by PowerBugi** [PowerShell/SecretManagement#105]
Hello,

Is it possible to dissociate the "modify" (set) command from the usual "create" (new) command ?

It's a bit confusing to do a "set" to create a new password, is there a reason ?

Thank you very much !

**Comment by JustinGrote** [comment]
@PowerBugi I think to keep the surface minimal, `New-Secret` is performed by `Set-Secret -NoClobber` which performs the same behavior. The default if setting a secret is to overwrite an existing secret, which matches the convention of the Powershell verbs as "Set" better.

You could easily make yourself an alias or function that calls Set-Secret -NoClobber. If there was enough demand for `New-Secret` as basically the same alias maybe, but what you want exists.

**Comment by PaulHigin** [comment]
This is correct.  We used to have `Add-Secret` that always overwrote an existing secret, and changed it to `Set-Secret` to be more accurate.
