### ISSUE TITLE
[Docs] Help is not correct for Set-Secret

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/SecretManagement#106]
The help shows
`Set-Secret [-Name] <String> [-Metadata] <Hashtable> [[-Vault] <String>] [<CommonParameters>]`

but is missing the `Secret`, `SecretInfo`, etc. parameters, and the help appears to have been clobbered with only the metadata scenario.

**Comment by SydneyhSmith** [comment]
Thanks for catching that @JustinGrote!

**Comment by PaulHigin** [comment]
Fixed in GA
