### ISSUE TITLE
PowerShell Gallery license link is not valid

### ISSUE THREAD

**Issue by CJHarmath** [PowerShell/SecretManagement#112]
The license at https://www.powershellgallery.com/packages/Microsoft.PowerShell.SecretsManagement/0.2.0-alpha1 points to https://github.com/PowerShell/Modules/License.txt which does not exists.

**Comment by SydneyhSmith** [comment]
Thanks @CJHarmath that is an deprecated/unlisted preview version on the module that was released under a different GitHub repository that has also since been archived....looks like the latest version of the module still points to that license and should be updated, thanks for catching that!

**Comment by PaulHigin** [comment]
Implemented in GA release
