### ISSUE TITLE
Issues Implementing $Metadata in Get-SecretInfo

### ISSUE THREAD

**Issue by joshcorr** [PowerShell/SecretManagement#116]
When trying to call the following in the extension I am developing

```
$vault_metadata= $(Invoke-VaultAPIQuery -VaultName $VaultName -SecretName $PSItem).data.metadata
$Metadata = [Ordered]@{}
$vault_metadata.psobject.properties | ForEach-Object { $Metadata[$PSItem.Name] = $PSItem.Value }

[Microsoft.PowerShell.SecretManagement.SecretInformation]::new(
    "$PSItem",
    "String",
    $VaultName,
    $Metadata)
 ```
 
  I receive the following error:
  ``` 
Exception             : System.Management.Automation.MethodException: Cannot find an overload for "new" and the argument count: "4".
                           at CallSite.Target(Closure , CallSite , Type , String , String , Object , Object )
                           at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
                           at System.Management.Automation.Interpreter.DynamicInstruction`6.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodException
FullyQualifiedErrorId : MethodCountCouldNotFindBest
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
```

**Comment by joshcorr** [comment]
Reading the code here in [SecretManagement.KeePass.Extension](https://github.com/JustinGrote/SecretManagement.KeePass/blob/main/SecretManagement.KeePass.Extension/Public/Get-SecretInfo.ps1) from @JustinGrote it appears that I need to do a bit more with the Hashtable before passing it in as Metadata.

**Comment by JustinGrote** [comment]
I have a convertto-readonlydictionary function in my modules that you can use for the hash table conversion

**Comment by joshcorr** [comment]
Thanks. I saw that. Was just hoping that adding the metadata would be a little easier to implement, and the error made me think that it didn't take 4 arguments.

**Comment by JustinGrote** [comment]
@joshcorr you can always do `new` without the parens to see all the potential constructors.

I agree this is not ideal and have asked @PaulHigin to adopt a hashtable constructor in https://github.com/PowerShell/SecretManagement/issues/108

**Comment by joshcorr** [comment]
Hopefully this changes. For the time being I went ahead and used your code [here](https://github.com/joshcorr/SecretManagement.Hashicorp.Vault.KV/blob/faf2bcc6a04fa0f8b607a1d59639f5647474a1bc/src/SecretManagement.Hashicorp.Vault.KV.Extension/SecretManagement.Hashicorp.Vault.KV.Extension.psm1#L61) and [here](https://github.com/joshcorr/SecretManagement.Hashicorp.Vault.KV/blob/faf2bcc6a04fa0f8b607a1d59639f5647474a1bc/src/SecretManagement.Hashicorp.Vault.KV.Extension/SecretManagement.Hashicorp.Vault.KV.Extension.psm1#L476)

**Comment by PaulHigin** [comment]
Yes, I agree and will add the new constructor.  I'll close this as a duplicate to #108 .
