### ISSUE TITLE
Exception on type initializer

### ISSUE THREAD

**Issue by bravo-kernel** [PowerShell/SecretManagement#120]
Awesome module and 0.9.1 works great on one of our machines but running `Get-SecretVault` is throwing the following exception on a pristine Windows Server 2016:

```
Get-SecretVault : The type initializer for 'Microsoft.PowerShell.SecretManagement.RegisteredVaultCache' threw an exception.
```

Any ideas/pointers on what could be causing this?

Thanks in advance ❤️

**Comment by PaulHigin** [comment]
This exception is thrown usually when an incompatible .Net binary is loaded.  SecretManagement and SecretStore are both PowerShell binary modules and so only one version of the module binary can be loaded in .Net before you need to start a new instance of PowerShell.  This is just a known issue with PowerShell binary modules.

To be safe you should always uninstall any earlier versions of SecretManagement (and SecretStore if you are using the extension vault) before installing a new version.  Also try starting a new PowerShell instance (but this isn't always needed).

```powershell
Get-Module -Name Microsoft.PowerShell.Secret* -List
Uninstall-Module Microsoft.PowerShell.SecretStore -Force
Uninstall-Module Microsoft.PowerShell.SecretManagement -Force
...
```

Also you can usually get more information on the error by looking at error exception and inner exceptions.  Many times PowerShell will bury the original exception.

```powershell
$err = Get-Error
$err.Exception
$err.Exception.InnerException
...
```

**Comment by bravo-kernel** [comment]
Thank you for the quick reply and the very good `Get-Error` pointer.

The issue was indeed caused by an incompatible .Net version and resolved by:

1. installing [.Net 4.7.2](https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-7-2-offline-installer-for-windows-05a72734-2127-a15d-50cf-daf56d5faec2) 
2. then re-installing the modules as explained above

Much love ❤️
