### ISSUE TITLE
Feature Request: Roboform vault extension

### ISSUE THREAD

**Issue by tstager** [PowerShell/SecretManagement#122]
I noticed that the gallery has modules for most commercial password programs except for RoboForm. I would like to request that a RoboForm vault be added if possible. If there is a procedure for requesting this from the third-party program let me know and I will request the feature there.

**Comment by SydneyhSmith** [comment]
Hi @tstager thanks for opening this issue-- apologies for the delayed response-- you will need to submit that request to RoboForm (or you may be create the vault extension yourself)

**Comment by tstager** [comment]
Thanks I will do that. This is a great project.

Trent

Sent via the Samsung Galaxy Note10+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
