### ISSUE TITLE
Test-SecretVault failure

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/SecretManagement#127]
I have no problems using the LastPass vault I have setup. But testing fails.
![image](https://user-images.githubusercontent.com/12089920/114785529-d44eb200-9d4a-11eb-8d06-8a6ca7b21102.png)

Is the failure from the LastPass extension or the Test-SecretVault command? The command offers no insight as to what it is testing so I have no way of knowing.

**Comment by PaulHigin** [comment]
The function of `Test-SecretVault` is implemented by the extension vault, in this case `SecretManatgement.LastPass.Extension`. The implementation should write errors if the test fails, but SecretManagement does not enforce this.

Please create an issue for the last pass extension vault:
https://github.com/TylerLeonhardt/SecretManagement.LastPass

**Comment by jdhitsolutions** [comment]
Filed an issue in the LastPass extension repo.
