### ISSUE TITLE
Get-Secret fails in pipeline

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/SecretManagement#130]
According to the help, I should be able to pipe `Get-SecretInfo` to `Get-Secret`.  But this no longer works. Even though I can run `Get-Secret` on its own.

![image](https://user-images.githubusercontent.com/12089920/114877910-bd04d880-9dcd-11eb-8be3-b46b386f4754.png)

I get the same result in both Windows PowerShell and PowerShell 7. I tried using my vault and the lastPass one I have, with the same error.

I also tested in a new PowerShell session.

**Comment by PaulHigin** [comment]
I am not able to repro this either on PowerShell 7 or Windows PowerShell.  What version of SecretManagement and SecretStore are you using?  Please always include version information along with platform.  Make sure you are using the latest GA releases of both modules, and be sure to uninstall any previous preview or RC module versinos.

**Comment by jdhitsolutions** [comment]
I'm using the 1.0.0 versions. But now I can't duplicate this problem either in Windows PowerShell or PowerShell 7.  So let's pretend we all have more important things to do. 😄
