### ISSUE TITLE
No BuiltInLocalVault when installing version 0.5.2-preview3

### ISSUE THREAD

**Issue by matswi** [PowerShell/SecretManagement#28]
Installed Microsoft.PowerShell.SecretManagement from Powershell Gallery with:
`Install-Module -Name Microsoft.PowerShell.SecretManagement -AllowPrerelease`
And the BuiltInLocalVault didn't get created. 
`PS C:\> Get-SecretVault
PS C:\>`
Uninstalling the latest version and installing version 0.2.1-alpha1 created the BuildInLocalVault.

Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎2020-‎03-‎03
OS build	19042.508
Experience	Windows Feature Experience Pack 120.2212.31.0

**Comment by PaulHigin** [comment]
The Built-In vault has been removed from this version.  For more information see blogs:
https://devblogs.microsoft.com/powershell/secretmanagement-preview-3/
https://devblogs.microsoft.com/powershell/secretmanagement-module-preview-design-changes/

The built-in vault was based on CredMan which is Windows platform only.  We now have a cross platform store (Microsoft.PowerShell.SecretStore).  CredMan is still useful on Windows interactive sessions so I have created an 'example extension vault' based on CredMan that you can build and register (https://github.com/PowerShell/SecretManagement/tree/master/ExtensionModules/CredManStore).

You can access your old built-in vault secrets by uninstalling Microsoft.PowerShell.SecretManagement version 0.5.2 and reinstalling the old alpha version.  You will need to manually transfer these secrets to the new 0.5.2 version (with SecretStore vault).
