### ISSUE TITLE
A parameter cannot be found that matches parameter name 'DefaultVault'

### ISSUE THREAD

**Issue by TheBigBear** [PowerShell/SecretManagement#30]
If I follow the instructions on Sydneys' blog at https://devblogs.microsoft.com/powershell/secretmanagement-preview-3/ then  

step 3 says to run: 

```"Register-SecretVault -Name SecretStore -ModuleName Microsoft.PowerShell.SecretStore -DefaultVault:```, 

but for me that results in a red error message 

```"A parameter cannot be found that matches parameter name 'DefaultVault'""```

**Comment by TheBigBear** [comment]
👍

**Comment by PaulHigin** [comment]
Be sure and uninstall (or just manually remove) any older version of SecretManagement module.  SecretStore is compatible only with SecretManagement version 0.5.2-preview3.  Get-Module should show only the latest version installed:
```powershell
Get-Module microsoft.powershell.secretmanagement -list

    Directory: C:\Users\user\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Binary     0.5.2      preview3   Microsoft.PowerShell.SecretManagem… Core      {Register-SecretVault, Unregister-Secre…
```

**Comment by TheBigBear** [comment]
@PaulHigin I had uninstalled all previous modules using -AllVersions . But di don't mention this was/is on a Mac. Same command works on Windows. So the SecretStore has no '-DefaultVault' on a Mac not even the new .Net Microsoft.PowerShell.SecretStore one? I thought this was now supposed to be cross platform and support this new Vault on all?

**Comment by PaulHigin** [comment]
Actually I haven't tested this on a Mac yet.  I have tested it on Ubuntu 18.04 and all behaviors and tests run as expected.
I'll test on Mac today, but I would be very surprised if it didn't work there.  But will let you know.

**Comment by PaulHigin** [comment]
I have tested this on a Mac and have not been able to repro this issue.  I can only think that you may still have an older version of SecretManagement installed.  The Mac I tested on didn't have any previous versions and this worked:

```powershell
Install-Module Microsoft.PowerShell.SecretManagement -AllowPrerelease -Repository PSGallery
Install-Module Microsoft.PowerShell.SecretStore -AllowPrerelease -Repository PSGallery
Register-SecretVault -Name SecretStore -ModuleName Microsoft.PowerShell.SecretStore -DefaultVault
```

**Comment by PaulHigin** [comment]
Closing this as answered.

**Comment by TheBigBear** [comment]
@PaulHigin ok, I retested as well, and even though I had used uninstall-module for both the Store and Management there were still files left over. See my log below ( or is this expected? are those dlls supposed to be leftover on the Mac after an uninstall-module ? ) (they had been installed using -Scope AllUsers - if that makes any diff? )

```
PS /Users/user> Uninstall-Module Microsoft.Powershell.SecretStore -AllVersions                                                                                                         

PS /Users/user> Uninstall-Module Microsoft.Powershell.SecretManagement -AllVersions                                                                                                    

PS /Users/user> Get-Module Microsoft.PowerShell.*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     0.5.2      preview3   Microsoft.PowerShell.SecretManagem… {Get-Secret, Get-SecretInfo, Get-SecretVault, Register-SecretVault…}
Binary     0.5.1      preview1   Microsoft.PowerShell.SecretStore    {Get-SecretStoreConfiguration, Reset-SecretStore, Set-SecretStoreConfiguration, Unlock-SecretStore…}

PS /Users/user> Remove-Module Microsoft.PowerShell.SecretManagement -
Force                Confirm              Debug                WarningAction        ErrorVariable        InformationVariable  OutBuffer            
WhatIf               Verbose              ErrorAction          InformationAction    WarningVariable      OutVariable          PipelineVariable     

PS /Users/user> Remove-Module Microsoft.PowerShell.SecretManagement -Force -Verbose
VERBOSE: Performing the operation "Remove-Module" on target "Microsoft.PowerShell.SecretManagement (Path: '/Users/user/.local/share/powershell/Modules/Microsoft.PowerShell.SecretManagement/0.5.2/Microsoft.PowerShell.SecretManagement.dll')".

PS /Users/user> Remove-Module Microsoft.PowerShell.SecretStore -Force -Verbose     
VERBOSE: Performing the operation "Remove-Module" on target "Microsoft.PowerShell.SecretStore.Extension (Path: '/Users/user/.local/share/powershell/Modules/Microsoft.PowerShell.SecretStore/0.5.1/Microsoft.PowerShell.SecretStore.Extension/Microsoft.PowerShell.SecretStore.Extension.psm1')".
VERBOSE: Performing the operation "Remove-Module" on target "Microsoft.PowerShell.SecretStore (Path: '/Users/user/.local/share/powershell/Modules/Microsoft.PowerShell.SecretStore/0.5.1/Microsoft.PowerShell.SecretStore.dll')".

PS /Users/user> Get-Module Microsoft.PowerShell.*                                  

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------

```

Now that I used remove-module for Store and Management after having uninstalled those two first I am now re-installing it and it accepts the ```-DefaultValue``` parameter.

**Comment by TheBigBear** [comment]
@PaulHigin , sorry to come back on this again. I have now redone it and this time I removed all traces again of both modules and then installed it with ```'-Scope AllUsers'``` ( like I had done at the very beginning ) and if I install it for all users then it actually tells me that the parameter ```'-DefaultValue'``` does not exist. 
Thinking about it, this might even be expected?

**Comment by PaulHigin** [comment]
I'm sorry you are having so much trouble with this.  We know that PowerShellGet (V2 and V3) has trouble with prerelease modules with dependencies.  I hope it gets addressed soon.  I am guessing it is installing the wrong version.

Try removing the modules again and installing only using the command lines I show above.  When I was experimenting before, I ran into different PowerShellGet install issues, but after I found the above command lines worked I didn't look into it any deeper.

If you need to move the module location (for AllUsers access), you can do that manually by simply copying the directories.
Not an ideal situation I agree, but should get you going.
