### ISSUE TITLE
Unable to find dependent module(s) (Microsoft.PowerShell.SecretManagement)

### ISSUE THREAD

**Issue by TheBigBear** [PowerShell/SecretManagement#31]
If I use the parameter ```"-Force"``` when installing the SecretStore it fails with error message : 

```"Unable to find dependent module(s) (Microsoft.PowerShell.SecretManagement)"``` but IF I leave the ```"-Force"``` off 

it will prompt me with: 

```
Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"):
```

and I can proceed with ```"A"``` and install it.

**Comment by PaulHigin** [comment]
Yeah, PSGetV2 has problems with preview release versions.

**Comment by PaulHigin** [comment]
PSGetV3 has even worse behavior with prerelease versions.  I'll create an Issue there to get it fixed.

**Comment by PaulHigin** [comment]
There was already a PSGetV3 issue opened for this.  It is unfortunate prerelease module versions with dependencies has these issues, since it affects these modules.  Workaround is to install each module separately.

**Comment by boernsen-development** [comment]
Is there any workaround for this if I want to overwrite an installed package with the same version as before?
