### ISSUE TITLE
How do I create or use the dll?

### ISSUE THREAD

**Issue by Agazoth** [PowerShell/SecretManagement#32]
All the new bits are installed and working as described, but how do I compile the dll for my extension?

**Comment by PaulHigin** [comment]
I use DotNet CLI tools, same as with [PowerShell Core builds](https://github.com/powershell/powershell#building-the-repository).
You can look at [CredManStore](https://github.com/PowerShell/SecretManagement/tree/master/ExtensionModules/CredManStore) extension vault example for details.

I rely on PowerShell Core tools to set up all of the DotNet tools to build there.  Once your run `Start-PSBootstrap', my CredMan builds fine.

Or you can build with VisualStudio.

**Comment by Agazoth** [comment]
Thanks :-)
