### ISSUE TITLE
Keepass

### ISSUE THREAD

**Issue by thenecroscope** [PowerShell/SecretManagement#34]
Do you have an examples yet for implementing with keepass by anychance? Thanks

**Comment by PaulHigin** [comment]
No, I am hoping someone in the community will do this, based on the example extension modules.

**Comment by thenecroscope** [comment]
OK thanks for the quick response. Hashi Corp key vault would be another good one also for the community.

**Comment by JustinGrote** [comment]
@thenecroscope 
I made a Keepass Module
https://twitter.com/JustinWGrote/status/1308534809463906305

**Comment by PaulHigin** [comment]
Awesome!
