### ISSUE TITLE
Pipeline support

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/SecretManagement#36]
Some examples:

```pwsh
Get-SecretInfo | Get-Secret

Get-SecretInfo | Set-Secret

Get-SecretInfo | Remove-Secret
```

**Comment by PaulHigin** [comment]
Get-Secret and Remove-Secret already takes the name from the pipeline.  I'm not sure if `Get-Secret | Set-Secret` makes sense...

**Comment by SydneyhSmith** [comment]
Sounds like Get | Set makes the sense in a multi-vault context as a migration pattern

**Comment by PaulHigin** [comment]
Added more pipeline support to preview4.
