### ISSUE TITLE
Passing SecureStringSecret to extensions from Set-Secret

### ISSUE THREAD

**Issue by Agazoth** [PowerShell/SecretManagement#37]
When passing SeureStringSecrets to the SecretStore, the secret is placed in the SecretStore. What is passed from the Set-Secret cmdlet to the extension? I want to pick up the SecureString in my extension, but what should I expect?

**Comment by PaulHigin** [comment]
Whatever type is passed to 'Set-Secret' is passed on to the extension vault.  So a SecureString type is passed as SecureString, and plain text types are passed as String types.  However, when 'Get-Secret' returns a secret, and that secret type is String or SecureString, a SecureString object is always returned.  The '-AsPlainText' switch must be used to have either type returned as a String object.

```powershell
PS > Get-Secret MySecret
System.Security.SecureString

PS > Get-Secret MySecret -AsPlainText
MySecretString
```

**Comment by PaulHigin** [comment]
Closing this as answered.  Re-open if you have more questions.
