### ISSUE TITLE
Register-SecretVault should import a module with -Force

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/SecretManagement#38]
I'm working on crafting an extension and what's kinda annoying is having to create a new PowerShell session every time I make a change to my implmenting script extension.

I wish I could just run this:

```pwsh
Unregister-SecretVault -Name foo
Register-SecretVault -Name foo -ModuleName .
```

And be ready to go with out a restart of my PowerShell session.

**Comment by PaulHigin** [comment]
I think adding a -Force to replace an existing secret vault module is a good idea.  However, if your vault module is binary based you will need to restart your PowerShell session.  This is just PowerShell/.NET and has nothing to do with SecretManagement.

**Comment by TylerLeonhardt** [comment]
I know it's a PowerShell/.NET behavior and you can't do anything for binary modules but it would certainly make the dev experience better :) plus I think we'll see a bunch of script extensions which wrap CLIs so this would help with all of those.

**Comment by SydneyhSmith** [comment]
Thanks everyone we made the decision to use the -AllowClobber switch rather than -Force

**Comment by PaulHigin** [comment]
Added -Force for import.  Also added ability to overwrite existing vault.  Preview4.
