### ISSUE TITLE
Request: Register-SecretVault should have ModuleName as Position 0 Parameter and Name Optional

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/SecretManagement#42]
For a ease of use improvement, if `ModuleName` is in Position 0 and Name is optional, then the vault name should be the same as the ModuleName by default if one isn't supplied, facilitating easier and more terse usage if a user doesn't want a custom Vault Name.

For instance:

```powershell
Register-SecretVault Keepass #Implies -ModuleName KeePass
#Will Create a vault named 'KeePass' that can be referenced easily
Set-Secret -VaultName KeePass -Name MySecret -Secret 'ok'
```

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote this is a perfectly reasonable request, cant think of any reason why this wouldnt have a nice behavior--thanks!

**Comment by PaulHigin** [comment]
Added in Preview4.
