### ISSUE TITLE
Feature Request: VaultParameters as dynamic Parameters

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/SecretManagement#44]
A secret module could expose the common parameters it uses via a typed hashtable or even as dynamic params, and SecretManagement could present the parameters dynamically once the vaultname is selected.

For instance, if a `KeePass` extension defined a `Path` and `MasterKey` VaultParameters, then the following could be possible to do temporary overrides of the existing vault configuration, which could be more intuitive for specifying noninteractive parameters such as credentials.

```powershell
Get-Secret -VaultName KeePass -Name MySecret -Path my\special\path -MasterKey (Get-Credential)
```

See InvokeBuild for an example of this in action, parameters defined in the build script are available to the Invoke-Build command.
https://github.com/nightroman/Invoke-Build/wiki/Script-Tutorial#script-parameters-for-tasks

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote this would be a significant change to the design of the module so we'd love to see more user feedback/justification for this change.  In general we prefer not to make this change because one of the goals of the module is to create a standard user interface and this would create deviation-- but want to leave this open to more discussion

**Comment by ThomasNieto** [comment]
@SydneyhSmith I completely understand the desire to create a standard user interface with minimal deviation, but there are cases where additional information is required.  

As its currently written there is no way to pass information to the underlying vault extension when calling any `*-Secret` cmdlets.  The way I understand `VaultParameters`, they are not actually vault parameters but are in fact static vault configuration. At first it did confuse me as it sounded like a way for a vault author to add custom parameters to the `*-Secret` cmdlets.

If you don't want to confuse the user by adding dynamic parameters and parameter sets. I would recommend adding a `-VaultParameters` (or another name) hashtable parameter to each `*-Secret` command to allow users to pass runtime information to the vault extension. Then turn the current static `VaultParameters` into `VaultConfiguration`. That allows for static one time configuration to be set for the vault and allow for runtime configuration to `*-Secret` cmdlets while keeping the cmdlet syntax simple.

**Comment by JustinGrote** [comment]
There are also some inconsistencies that ideally should be cleaned up, e.g. `-VaultName` vs `-Vault` when they both accept the same string input. `-Vault` should be a vault object whereas `-VaultName` can be a string. Both could be added to all commands to avoid any breaking changes.

**Comment by SydneyhSmith** [comment]
We believe this issue is resolved by the additional flexibility we have provided to vault authors in preview 3...we have also cleaned up the vault parameters for consistency.
