### ISSUE TITLE
[Preview3] $AdditionalParameters is not passed to Test-SecretVault

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/SecretManagement#45]
The vault parameters are not passed to Test-SecretVault as `$AdditionalParameters`

### Workaround
`(Get-SecretVault $VaultName).VaultParameters`

**Comment by PaulHigin** [comment]
I am not sure what you mean by this.  I have verified that registered vault parameters are passed as `&AdditionalParameters` to implementing cmdlets, so I am not sure what your scenario is.  Please always include repro steps and version information in bug reports.

**Comment by JustinGrote** [comment]
@PaulHigin apologies for that.

Upon further review I've found this is because my extension cmdlets are leaking into the main runspace
![image](https://user-images.githubusercontent.com/15258962/93930485-4c338d00-fcd2-11ea-9ddc-fbf85157f932.png)

Not sure what's going on here, they're listed as a nestedmodule but the functions are showing up in exportedfunctions for some reason. Will report back once I figure out what's going on as it may be helpful to other authors.
![image](https://user-images.githubusercontent.com/15258962/93930821-cc59f280-fcd2-11ea-9009-fbb98252aedd.png)

**Comment by JustinGrote** [comment]
Found my problem, in the base module you explicitly need to specify FunctionsToExport = @() or else it will include all functions **including those of nested modules**. Annoying little quirk. Adding that fixed it and closing this issue.

![image](https://user-images.githubusercontent.com/15258962/93932387-f14f6500-fcd4-11ea-8fd9-08775cb77835.png)

**Comment by PaulHigin** [comment]
Ok, good to know.  I remember struggling with this myself.  I had issues where my `.Extension` module would expose the `Get-Secret, Set-Secret, ...` nested commands in the user space if it was binary and depended on another module that exported cmdlets.
