### ISSUE TITLE
when gathering the secret for set-secret we could tell the user the name of the secret

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/SecretManagement#53]
```powershell
PS> set-secret -name testsecret 

cmdlet Set-Secret at command pipeline position 1
Supply values for the following parameters:
SecureStringSecret: 
```

It might be nice to tell the user "provide the secret for 'testsecret" as the prompt

**Comment by SydneyhSmith** [comment]
Thanks @JamesWTruher that message comes from PowerShell, and does not have a hook for us to use so we will need to move this issue to the PowerShell/PowerShell repo

**Comment by PaulHigin** [comment]
Closing as won't fix, since it is a PowerShell parameter binding feature.
