### ISSUE TITLE
Test-SecretVault does not take wildcards for -Name parameter

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/SecretManagement#56]
It is not easy to test all the secret vaults as the name parameter does not take wildcards. Get-SecretVault does take wildcards for name which set the expectation that Test-SecretVault will accept it too.

## Current state:
PS /> Get-SecretVault

Name         ModuleName                       IsDefaultVault
----         ----------                       --------------
SecretStore  Microsoft.PowerShell.SecretStore False
SecretStore2 Microsoft.PowerShell.SecretStore True

## Actual 
PS /> Test-SecretVault -name *
Test-SecretVault: Vault not found in registry: *

## Expected
Should test all registered secret vaults.

## Workaround

Get-SecretVault -Name * | Test-SecretVault

**Comment by PaulHigin** [comment]
Implemented for preview5.
