### ISSUE TITLE
`Unregister-SecretVault -Name` probably should support wildcards

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/SecretManagement#57]
It's convenient to run `Unregister-SecretVault *` to remove all my secret vaults at once.

**Comment by SydneyhSmith** [comment]
Thanks @daxian-dbw this is by design because Unregistering is a destructive action,
the workaround would be to use piping...what do you think?

**Comment by daxian-dbw** [comment]
`Remove-Item` is a destructive action, but it supports wildcards, so I don't think that's a strong argument to not support wildcards for `Unregister-SecretVault`.

**Comment by iSazonov** [comment]
I have concerns too. The use of the pipeline could be better. Or at least we need to protect ourselves with Should and Force.

**Comment by PaulHigin** [comment]
Implemented in preview6.
