### ISSUE TITLE
`Unregister-SecretVault -Name` should be of type `string[]` instead of `string`

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/SecretManagement#58]
`Unregister-SecretVault` should allow removing multiple vaults at once.

**Comment by SydneyhSmith** [comment]
@daxian-dbw I am curious what the use case would be for unregistering multiple vaults at a time...what were you hitting when you wanted this feature?

**Comment by daxian-dbw** [comment]
I was playing the module and registered multiple vaults using `Register-SecretVault`, and then I'm done trying things and try to remove all. Then I found I had to remove one at a time.

**Comment by PaulHigin** [comment]
Implemented in preview6.
