### ISSUE TITLE
Extensions should be able to hook into `Unregister-SecretVault`

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/SecretManagement#60]
Would like a way to have my extension called when `Unregister-SecretVault` is used with my extension.  The scenario is I may want to clean up all the secrets stored via my vault from PowerShell.  

KeyChain, for example, allows me to create a new keychain just for my extension that wouldn't be mixed with other secrets already stored in keychain for a user.  If they unregister my extension, it would mean they no longer need to use it so I should clean out their secrets.

We would also need to decide if the user opts in or out of cleaning out those secrets by default.

**Comment by SydneyhSmith** [comment]
Thanks @SteveL-MSFT, Paul and I were discussing for symmetry we may also want to add a hook for Register-SecretVault....

@TylerLeonhardt and @JustinGrote curious to hear your input as vault extension developers

**Comment by JustinGrote** [comment]
As my previous, I don't see any harm it having it be available but optional. I understand the rationale in allowing for offline configuration and later operation, but that logic could be done by the Extension author if required in the register-secretvault hook by testing for availability or whatnot.

**Comment by TylerLeonhardt** [comment]
I agree. :) an Unregister would be great.

**Comment by SteveL-MSFT** [comment]
Yes, definitely optional and not mandatory as it wouldn't apply to all extensions.  Although for my use case, it may make sense to have a `-RemoveSecrets` switch to inform the extension to do clean-up while otherwise there may be some other unregistration operations it would do.

**Comment by TylerLeonhardt** [comment]
> Although for my use case, it may make sense to have a -RemoveSecrets switch

Probably should just have the hashtable for additional properties just like the other cmdlets instead.

**Comment by PaulHigin** [comment]
I made the `Unregister-SecretVault` an optional function for a vault extension.  It will be called before the extension is removed from the registry.  Parameters will just be 'VaultName' and 'AdditionalParameters'.

```powershell
function Unregister-SecretVault
{
    param (
        [string] $VaultName,
        [hashtable] $AdditionalParameters
    )
...
}
```

**Comment by PaulHigin** [comment]
Implemented for preview5.
