### ISSUE TITLE
The single only available secret vault should be made default automatically

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/SecretManagement#61]
The single only available secret vault should be made default automatically.

When running `Register-SecretVault -Name MyStore -ModuleName Microsoft.PowerShell.SecretStore` or `Unregister-SecretVault SecretStore`, if the action results in only a single vault being present, then that vault should be made 'Default' automatically.

This will make the following scenario much intuitive:
```
## Register the very first vault

PS> Register-SecretVault -Name MyStore -ModuleName Microsoft.PowerShell.SecretStore
PS> Set-Secret -Name nuget -Secret abc
Set-Secret: Unable to set secret because no vault was provided and there is no default vault designated.
```

**Comment by SydneyhSmith** [comment]
Thanks @daxian-dbw this is an interesting idea, we are worried about the case when the user then does add more vaults and may not expect it to be the first to be default vault...but happy to hear more feedback on this

**Comment by daxian-dbw** [comment]
I think we should consider what would be the common case for most users -- having multiple vaults registered? Or having only the `M.P.SecretStore` vault registered. If we think the latter would be the common case for most users, then making the single only registered vault the default vault would be intuitive.

**Comment by iSazonov** [comment]
I agree that the first vault should be default. As for "when the user then does add more vaults" I think we could add -Default switch so that users can explicitly set default.

**Comment by PaulHigin** [comment]
Implemented in preview6.
