### ISSUE TITLE
Needs better documentation about `-SecureStringSecret` in `Set-Secret`

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/SecretManagement#62]
This is the syntax of `Set-Secret`:

```
SYNTAX
    Set-Secret [-Name] <String> [-Secret] <Object> [[-Vault] <String>] [-NoClobber] [<CommonParameters>]

    Set-Secret [-Name] <String> [-SecureStringSecret] <SecureString> [[-Vault] <String>] [-NoClobber] [<CommonParameters>]
```

And this is the current documentation about `-Secret` and `-SecureStringSecret`:
```
    -Secret <Object>
        A secret value to be added. The object type must be one of the supported types.

        Required?                    true
        Position?                    1
        Default value                None
        Accept pipeline input?       True (ByValue)
        Accept wildcard characters?  false

    -SecureStringSecret <SecureString>
        A secret SecretString object to be added.

        Required?                    true
        Position?                    1
        Default value                None
        Accept pipeline input?       True (ByValue)
        Accept wildcard characters?  false
```

The parameter `-Secret` is able to accept `SecureString` object, so it's not clear when should a user uses `-SecureStringSecret`.
@PaulHigin's clarification on this is:
> `-SecureStringSecret` is the default parameter set and when no parameter is supplied will prompt the user to safely type in a secret string

We probably need better documentation about `-SecureStringSecret` so it's less confusing to users.

**Comment by SydneyhSmith** [comment]
We can add further clarification of this behavior-- https://github.com/PowerShell/SecretManagement/blob/master/help/Set-Secret.md#description

**Comment by SydneyhSmith** [comment]
Closed as fixed
