### ISSUE TITLE
Verbose / Debug flags should be passed down to the implementing module

### ISSUE THREAD

**Issue by itfranck** [PowerShell/SecretManagement#66]
Verbose / Debug from the Microsoft.Powershell.SecretManagement module get printed all right but  are not passed down to  the implementing module.

If I had these two lines at the top of the Get-SecretInfo implementation,  here is what I get when I call `Get-SecretInfo -Verbose`

```
# Forcing verbose on purpose so I can see the value.
Write-verbose -message ($PsboundParameters | out-string) -verbose
write-verbose -message "`$VerbosePreference: $VerbosePreference" -verbose
```
![image](https://user-images.githubusercontent.com/1980296/96319428-a677f300-0fdd-11eb-906c-293d4d1e165b.png)

Observed here: 
https://github.com/TylerLeonhardt/SecretManagement.LastPass/pull/4

**Comment by PaulHigin** [comment]
Implemented -Verbose for preview5.  No -Debug support though.

**Comment by TylerLeonhardt** [comment]
Can this stay open for Debug support then?

**Comment by PaulHigin** [comment]
No, we decided not to add debug support.

**Comment by TylerLeonhardt** [comment]
I'm curious why. Seems odd to single that out. Makes me wonder if the `*Action` and `*Variable` parameters are supported.

**Comment by PaulHigin** [comment]
The extension vault script functions are not meant to be normal cmdlets that support common parameters.  Instead they are contract interfaces for implementing a valid extension vault.  We made an exception for 'Verbose' because it seemed valuable for debugging purposes.

**Comment by ThomasNieto** [comment]
@PaulHigin did you explicitly prevent these "interfaces" from writing to other streams (Debug, Info)? If not then the module author could bypass them with the preference variable or by using `Write-Debug -Debug`. My opinion is that all streams should be available to vault authors.

**Comment by PaulHigin** [comment]
No, the extension vault functions are called on the UI thread, and so can write to any cmdlet data stream.  But the extension vault interface is just simple PowerShell functions that take pre-defined parameter arguments plus the `AdditionalParameters` hash table.  No common parameters are supported, except now where just the `-Verbose` parameter is passed automatically to `AddtionalParameters` hash table.  There are no plans to support any other common parameters.
