### ISSUE TITLE
Get-Secret not supporting wildcard characters yet preventing their uses as regular characters.

### ISSUE THREAD

**Issue by itfranck** [PowerShell/SecretManagement#67]
https://github.com/PowerShell/SecretManagement/blob/aef03a1cccbec8b45ef134a6ad922ab8bf57c74e/src/code/SecretManagement.cs#L848

            // Wild card characters are not supported in this cmdlet.

The current `Get-Secret` implementation do not support wildcards.
This is perfectly fine.

String should be interpreted literally when querying the secret name.
So : 
- "MySecret*xy"
- "MySecret [Id: 1029301]"

should fetch the corresponding secrets with that literal name. 

The current behavior is weird.
If the cmdlet is not supporting wildcards, I don't expect it to throw an error.
I expect it to process the string literally, which it is what it does, despite the error.

The error is unwanted here. 

See: Using SecretManagement.Lastpass module, I get the result properly, as wildcards are not supported.
Unlike any other cmdlet not supporting wildcards, I would expect NOT to have an error here. 
![image](https://user-images.githubusercontent.com/1980296/96355731-e8269d80-10b2-11eb-82da-d4054b115635.png)

Edit: 
Also, escaping the wildcard (like if it was a wildcard function) will not produce the error but will be passed down literally. 

Related Issue: 
https://github.com/TylerLeonhardt/SecretManagement.LastPass/pull/5

**Comment by itfranck** [comment]
@TylerLeonhardt  For your information. In my opinion, this belong here. We shouldn't have had to change anything on the Lastpasss end (Although no regret, parenthesis are still better looking 😄 )

**Comment by PaulHigin** [comment]
This is just PowerShell behavior.  Certain characters are reserved as wildcards and are not allowed as literal characters.  So this behavior is by design.

**Comment by TylerLeonhardt** [comment]
So there's no way for me to have `[ ]` or `*` in my secret name? It's impossible with SecretManagment?

**Comment by itfranck** [comment]
> This is just PowerShell behavior. Certain characters are reserved as wildcards and are not allowed as literal characters. So this behavior is by design.

A normal wildcard function would allow me to escape the bracket.
This does not work here. 

A normal wildcard function would also support wildcards.
This function does not.

A function that do not accept wildcard wouldn't prevent me from using any characters at all and would treat them literally.
That's actually what `Get-Secret` does, since as you can see in my initial screenshot, it does return the secret properly despite the error. 

If this is by design, this is a design I didn't see ever before.
I still think this is not supposed to behave like this.
The wildcard error do nothing but producing an error that serve no purpose.
In the end, the string is processed literally anyway and the secret is returned correctly.

To take another context, if I try 
`Invoke-Command -ComputerName 'loc*' -ScriptBlock {}`, I don't get an error stating that ComputerName does not accept wildcards, instead, it look for a computer name named literally **loc*** and ultimately return an error because I don't have such a computer in my network.

**Get-Secret** return the value for my secret literally named **MySecret*** but do produce an error regarding wildcards.
That detract from what I expect from any cmdlet not using wildcards in the first place.

I hope this get considered again.

**Comment by PaulHigin** [comment]
This feels like an edge case to me.  Needing to use wild card characters in secret names seems very rare and something easily avoided.  Also, allowing wild card characters as literals would be confusing to most PowerShell users who expect wild card behavior.  We can certainly re-think this if there is a strong need, but right now it feels like a edge case feature.

**Comment by PaulHigin** [comment]
Actually, I thought about this some more and have changed my mind.  I don't see any real harm in allowing wild card characters as literals in the name.  The 'not found' error returned will inform a user that wild card characters are not treated as wild cards in the name.  So I will remove the restriction.

**Comment by itfranck** [comment]
> Actually, I thought about this some more and have changed my mind. I don't see any real harm in allowing wild card characters as literals in the name. The 'not found' error returned will inform a user that wild card characters are not treated as wild cards in the name. So I will remove the restriction.

What you seem to describe is the current behavior.

![image](https://user-images.githubusercontent.com/1980296/96650363-c7538780-1300-11eb-94cf-32671abab9d3.png)
Secret is returned but inform the user through an error. 

The reason I opened this is that there shouldn't be an error to inform the user at all.
The characters `*[]?` , in any other context where wildcard support is not implemented, always interpret the name literally without ever warning that there is no wildcard support through warning or error (But maybe that's what you meant?).

**Comment by PaulHigin** [comment]
No, currently you get an error if you use a wild card character.  Now, you can use it, but get an error if there is no name match:
```powershell
Get-Secret *
Get-Secret: The secret * was not found.
```
This should be clear to the user that there is no wild card action and is taking the name literally.

**Comment by TylerLeonhardt** [comment]
That sounds great!

**Comment by PaulHigin** [comment]
Implemented for preview5.
