### ISSUE TITLE
Install-Module for SecretStore fails if using -Force

### ISSUE THREAD

**Issue by kenlasko** [PowerShell/SecretManagement#72]
I want to add SecretManagement to a Linux Docker container running PS Core 7.0.3.  Since I'm using a dockerfile to build the image, I need to use the -Force parameter to bypass the "Are you sure" question prompt. 

The SecretManagement module installs just fine with -Force, but installing SecretStore throws the following error:

PS /nectar10> Install-Module Microsoft.PowerShell.SecretStore -AllowPrerelease -Force                                                    Install-Package: /opt/microsoft/powershell/7/Modules/PowerShellGet/PSModule.psm1:9709                                                    Line |                                                                                                                                   9709 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters                                                               |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to find dependent module(s) (Microsoft.PowerShell.SecretManagement)

I get the same issue when running the container interactively. However, if I remove the -Force parameter, the module installs just fine after I press Y. 

I can work around the issue by trusting the PSGallery store.

**Comment by PaulHigin** [comment]
This is a known issue with PowerShellGet V2, and dependent preview version modules.  It will be addressed in PowerShellGet V3.
