### ISSUE TITLE
Import-module failes on WS2016

### ISSUE THREAD

**Issue by JesperJ** [PowerShell/SecretManagement#73]
Import-module failes running PS 5.1 on Windows Server 2016.
I don't know if this is just my machine or related to WS2016.

`PS H:\> import-module Microsoft.PowerShell.SecretManagement`
`import-module : Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral,
PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
import-module Microsoft.PowerShell.SecretManagement
CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand`

`PS H:\> $PSversiontable`
`Name                           Value
PSVersion                      5.1.14393.3471
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3471
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1`

`PS H:\> get-module Microsoft.PowerShell.SecretManagement -ListAvailable`
`Directory: C:\Program Files\WindowsPowerShell\Modules
ModuleType Version    Name                                ExportedCommands
Binary     0.5.3      Microsoft.PowerShell.SecretManag... {Register-SecretVault, Unregister-SecretVault, Get-SecretV...`

![image](https://user-images.githubusercontent.com/820747/97721754-21ef9f00-1aca-11eb-9adf-d5acab2b0ef8.png)

**Comment by PaulHigin** [comment]
Yes, I am currently building the module against the netstandard2.0 library.  This is compatible with WindowsPowerShell but you currently have to install the netstandard package (or install PowerShell 7.0).

But I'll look into building against the net472 library, which should remain compatible both with WindowsPowerShell and PowerShell 7.0, without having to install other packages.

**Comment by PaulHigin** [comment]
This should be fixed in the next preview release.

**Comment by PaulHigin** [comment]
Implemented in preview6.
