### ISSUE TITLE
Unregister-SecretVault : Item has already been added. Key in dictionary: 'verbose' Key being added: Verbose

### ISSUE THREAD

**Issue by itfranck** [PowerShell/SecretManagement#74]
![image](https://user-images.githubusercontent.com/1980296/98455788-4d662f80-2143-11eb-83cc-7f1ea4471fb9.png)

There seems to be a bug with the implementation of #66. 

Steps to reproduce : 

```
Register-SecretVault -ModuleName secretmanagement.lastpass -VaultParameters @{lpassCommand = 'wsl'; verbose = $true } -Name 'lpt10'
Unregister-SecretVault -Name lpt10 
```
I used SecretManagement.Lastpass but I assume the actual module implementation is relevant and any valid module could be put in there

Issue: 
I cannot unregister that keyvault anymore.

(In the end, I was able to remove the vault manually by tracking down the **secretregistryvault** location in the filesystem )

**Comment by PaulHigin** [comment]
I am not able to repro this, I am always able to unregister a secret vault.  But `Verbose` is now a reserved parameter name for extension vault cmdlets, and should not be used in `VaultParameters`.
