### ISSUE TITLE
`Set-DefaultVault` doesn't have the same prefix as other cmdlets

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/SecretManagement#79]
It's best practice for a module to have the same prefix for every cmdlet in a module so that users know that a cmdlet comes from a module... Or use a prefix that gives context to the user on what they are doing.

`Set-DefaultVault` doesn't have the prefix that the others do and I worry that it could stomp on an existing cmdlet since `Vault` is fairly overloaded in the key store space.

This cmdlet should either be `Set-SecretDefaultVault` or `Set-SecretVaultDefault`.

**Comment by itfranck** [comment]
My vote to the latter (`Set-SecretVaultDefault`).
It feels more aligned with other vault operations (Test-SecretVault / Register-SecretVault / UnregisterSecretVault)

**Comment by PaulHigin** [comment]
Changed for 1.0 RC1 release.
