### ISSUE TITLE
[0.9.0] Test-SecretVault Help Incorrect (-Vault instead of -Name)

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/SecretManagement#90]
`Test-SecretVault` help is incorrect in the built version, even though it is correct in the markdown.
![image](https://user-images.githubusercontent.com/15258962/104078270-0c85a800-51d2-11eb-9e06-05e464965456.png)
![image](https://user-images.githubusercontent.com/15258962/104078283-20310e80-51d2-11eb-8885-b5267918f64a.png)

**Comment by PaulHigin** [comment]
Fixed in RC2.

**Comment by PaulHigin** [comment]
Hmm, looks like this isn't fixed.  Reopening.

**Comment by PaulHigin** [comment]
Fixed in GA
