### ISSUE TITLE
VaultNameCompleter doesn't handle vaults with spaces in their names

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/SecretManagement#96]
If a vault has a space in its name, VaultNameCompleter does not wrap it in quotes when it is tab-selected

![Capture](https://user-images.githubusercontent.com/15258962/104806420-37509d00-578c-11eb-8338-3eb4ca0a0f53.gif)

**Comment by PaulHigin** [comment]
Duplicate of #91
