### ISSUE TITLE
SecretInformation objects should be pipeable to Get-Secret to retrieve specific secret

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/SecretManagement#97]
If I do a `get-secretInfo -filter 'selectASingleSecret' | get-secret`, it still searches all vaults, not fetching my specific secret from my specific vault

https://github.com/PowerShell/SecretManagement/blob/30991fd56ef43074c3ff76f303fbf35c9e46be7d/src/code/SecretManagement.cs#L1034-L1039

This should have an Alias of `VaultName` and also be `ValueFromPipeline = $true` in order to enable this functionality as `[SecretInformation]` has `VaultName` as a property.

There's lots of these inconsistencies that should be cleaned up with aliases I think to better support piping. 

Filter vs. Name, Vault vs VaultName, AdditionalParameters vs VaultParameters, etc.

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote we are having some trouble reproducing this,   `Get-SecretInfo -Name foo | Get-Secret`  does return the specified secret? Let us know if you have expected/actual result repro steps..thanks!

**Comment by JustinGrote** [comment]
@SydneyhSmith the point is that it doesn't just search the vault that secretinfo returned, it searches all vaults, so if there's another secret with the same name, it will return that too.

**Comment by PaulHigin** [comment]
I am seeing an issue but not as describe here.  Please always use the standard form for reporting bugs and including repro steps.

Get-Secret does not honor VaultName property when processing SecretInformation object input.
```powershell
PS > Set-Secret Secret1 "MySecretV1" -Vault Vault1
PS > Set-Secret Secret1 "MySecretV2" -Vault Vault2
PS > Get-SecretInfo Secret1 -Vault Vault2 | Get-Secret -AsPlainText

Expected:
"MySecret2"

Actual:
"MySecret1"


```

**Comment by PaulHigin** [comment]
Fixed in RC2.

**Comment by JustinGrote** [comment]
@PaulHigin thank you!
