### ISSUE TITLE
[SecretInformation] Should have Format .ps1xml that shows as table and truncates secret names

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/SecretManagement#98]
If you have a long secret name, running get-secretinfo will only show the "Name" property. It should autosize the table and show Type and Vault, and truncate the name

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote we do have a format.ps1xml file but we choose to rely on table autosize since we do not know the user's console size so we do not want to arbitrarily choose a size (following the pattern of the PowerShell formatter)-- PowerShell does support customizing format table
